version: '2'

volumes:
    hass-config:
    mosquitto:
    influxdb-data:

services:

  homeassistant:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./services/homeassistant
    ports:
      - 8123:8123
      - 6053:6053
    privileged: true
    volumes:
      - 'hass-config:/config'
    restart: always
    networks:
      hems:
        ipv4_address: 172.18.4.2

  mqtt:
    build: ./services/mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - mosquitto:/mosquitto/data
    networks:
      hems:
        ipv4_address: 172.18.4.7

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218"
    volumes:
      - 'hass-config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
    networks:
      hems:
        ipv4_address: 172.18.4.6

  influxdb:
    build: ./services/influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      hems:
        ipv4_address: 172.18.4.3

  nginx-reverse-proxy:
    build:
      dockerfile: ./Dockerfile
      context: ./services/nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
    networks:
      hems:
        ipv4_address: 172.18.4.4

  wifi-repeater:
    image: bh.cr/gh_scott_hamilton/wifi-repeater-block
    privileged: true
    # environment:
    #   # AP_SSID: hems-${BALENA_DEVICE_UUID:0:4}
    #   AP_PASSWORD: ${BALENA_DEVICE_NAME_AT_INIT}
    labels:
      io.balena.features.dbus: '1'
    networks:
      hems:
        ipv4_address: 172.18.4.5

  configurator:
    build: ./services/configurator
    privileged: true
    network_mode: host
    restart: on_failure

networks:
  hems:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.4.0/24
         gateway: 172.18.4.1
