version: '2'

volumes:
    hass-config:
    mosquitto:
    influxdb-data:

services:

  wifi-connect:
    image: balenablocks/wifi-connect:armv7hf
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    environment:
      PORTAL_LISTENING_PORT: 8080
      ACTIVITY_TIMEOUT: 120

  homeassistant:
    build: ./services/homeassistant
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'hass-config:/config'
    restart: always
    networks:
      hems:
        ipv4_address: 172.18.4.2

  mqtt:
    build: ./services/mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - mosquitto:/mosquitto/data

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218"
    volumes:
      - 'hass-config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config

  influxdb:
    build: ./services/influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      hems:
        ipv4_address: 172.18.4.3

networks:
  hems:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.4.0/24
         gateway: 172.18.4.1
