- alias: "Backup Home Assistant every night"
  triggers:
    - trigger: time
      at: "01:12:00"
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  actions:
    - alias: "Create backup now"
      action: backup.create

- alias: "Purge old backups"
  triggers:
    - trigger: time
      at: "02:12:00"
  action:
    - service: shell_command.purge_backups
